openapi: 3.0.3
info:
  title: Ping API
  description: API simple pour tester la disponibilité du serveur
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /ping:
    get:
      summary: Vérifie si le serveur répond
      responses:
        '200':
          description: Le serveur est joignable
          content:
            text/plain:
              schema:
                type: string
                example: pong
